# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:18761/eureka/

# Datasource and JPA configuration to be used for storing the OAuth authorization details 
# and token store
spring:
  datasource:
    data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show_sql: true
#    hibernate:
#      ddl-auto: create
  mail:
    host: localhost
    port: 25
    username:
    password:
project:
  mail:
    from: uaa@localhost
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours
        tokenValidityInSeconds: 86400