server:
  port: 8081

# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
  hostname: 127.0.0.1
  port: 8899
  contextPath: uua

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
spring:
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false